/*Using the result of the first challenge, every time the user hovers over a square, change its color to a random color generated by the function below:*/


var divElement = document.createElement('div');//create a div
document.body.appendChild(divElement);//put the div on the body 

var btnElement = document.createElement('button');//create a button
divElement.appendChild(btnElement);//put the button as a child of div
btnElement.setAttribute('id', 'button');//create a "id" on the button
btnElement.setAttribute('onClick', 'CreateSquare()');//create a function atribute
var textElement = document.createTextNode('Create'); //text inside the button
btnElement.appendChild(textElement);//put the text inside the button

function getRandomColor() {
    var letters = "0123456789ABCDEF";
    var color = "#";
    for (var i = 0; i < 6; i++) {
        color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
}


function CreateSquare() {
    let boxElement = document.createElement("div");

    boxElement.style.width = '100px';
    boxElement.style.height = '100px';
    boxElement.style.margin = '10px';
    boxElement.style.backgroundColor = '#f00';

    boxElement.addEventListener("mouseover", () => {
        let newColor = getRandomColor();
        boxElement.style.backgroundColor = newColor;
    });

    boxElement.classList.add('box');//add the box class
    divElement.appendChild(boxElement);
}
